# Use postgres/example user/password credentials
version: '3.7'

services:

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: Qwerty1234qwerty
      POSTGRES_USER: user
      POSTGRES_DB: user
